[theme]
base = "light"
primaryColor = "#2E3F8F"
backgroundColor = "#F4F6F9"
secondaryBackgroundColor = "#EAEDF2"
textColor = "#232838"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
