[theme]
base = "light"
primaryColor = "#1E2761"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#111827"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
